### ISSUE TITLE
Rename this repo to something more descriptive

### ISSUE THREAD

**Issue by victorporof** [ejpbruel/protolol#1]
Temporary code names for projects are fine, but a more descriptive title that could also potentially attract broader audiences seems like a good idea to consider. We may want to seriously think about this at some point in the near future after finalizing a first version of the protocol's internal framework and front-facing API.

After careful consideration and debating, given the long-term intention to possibly replace or fix protocol.js, our current remote debugging protocol framework, conversations seem to converge towards protolol.js. Depending on the actual direction this project ends up heading towards, trololol.js seems also acceptable, possibly suiting broader demands for a more descriptive name.

**Comment by ejpbruel** [comment]
RESOLVED: FIXED
